SYSTEMC_HOME      = /home/puneet/gsocs/gspm/OSCI/systemc/2.2/gcc4.0
TLM_HOME          = /home/puneet/gsocs/gspm/OSCI/tlm/
GREENSRC          = /home/puneet/gsocs/latest-svn-packages
GREENREG_DIR      = $(GREENSRC)/GreenReg/greenreg
GREENSIGNALBUS    = $(GREENSRC)/SignalSocket/signalsocket/
GREENSIGNALSOCKET = $(GREENSRC)/SignalSocket/signalsocket/green-signal-socket/include
GSGPSOCKET_DIR    = $(GREENSRC)/GSGPSocket
GREENSOCKET_DIR   = $(GREENSRC)/GreenSocket
GREENCONTROL_DIR  = $(GREENSRC)/GreenControl
GREENROUTER_DIR   = $(GREENSRC)/GreenRouter

ARCH_TARGET       = linux

SYSTEMC_INC_DIR   = $(SYSTEMC_HOME)/include
SYSTEMC_LIB_DIR   = $(SYSTEMC_HOME)/lib-$(ARCH_TARGET)
TLM_INC_DIR       = $(TLM_HOME)/include/tlm

#LUA_INC_DIR       = /home/puneet/gsocs/gspm/PUC-Rio/lua/5.1.3/gcc4.0/include
#LUA_LIB_DIR       = /home/puneet/gsocs/gspm/PUC-Rio/lua/5.1.3/gcc4.0/lib
#
#BOOST_HOME_DIR    = /home/puneet/gsocs/gspm/Boost/boost
#BOOST_INC_DIR     = $(BOOST_HOME_DIR)/include/boost-1_34_1
#BOOST_FS_LIB_DIR  = $(BOOST_HOME_DIR)/lib
#BOOST_FS_LIB_NAME = boost_filesystem-gcc40-1_34_1

GXX             = g++
#GCC             = gcc
#CC              = gcc
LD              = g++
