# Configuration of dependencies

DEPENDENCIES = GREENSOCS SYSTEMC TLM BOOST GREENREG

GREENSOCS_CPPFLAGS = -D_REENTRANT
GREENSOCS_INCLUDEDIR = /opt/greensocs/gs_tarball/bartho-test-install/include
GREENSOCS_LIBRARYDIR = /opt/greensocs/gs_tarball/bartho-test-install/lib
GREENSOCS_LIBRARIES = pthread

SYSTEMC_CPPFLAGS = -DUSE_STATIC_CASTS -DSC_INCLUDE_DYNAMIC_PROCESSES
SYSTEMC_INCLUDEDIR = /home/bartho/greensocs/packages/gsdevelopment/tools/new-systemc-2.3-final/include
SYSTEMC_LIBRARYDIR = /home/bartho/greensocs/packages/gsdevelopment/tools/new-systemc-2.3-final/lib-linux64
SYSTEMC_LIBRARIES = systemc

TLM_INCLUDEDIR = TLM_INCLUDE_DIRS-NOTFOUND
TLM_LIBRARYDIR = 
TLM_LIBRARIES = 

BOOST_INCLUDEDIR = /opt/greensocs/qemu-systemc-demo-2012-01-02/dependencies/boost/include/boost-1_34_1
BOOST_LIBRARYDIR = 
BOOST_LIBRARIES = 

GREENREG_INCLUDEDIR = /opt/greensocs/gs_tarball/greenlib/greenreg


################################
# GENERIC BELLOW HERE

# SYSTEMC_CPPFLAGS += $(addprefix -I,${SYSTEMC_INCLUDEDIR})
# SYSTEMC_LDFLAGS = $(addprefix -L,${SYSTEMC_LIBRARYDIR})
# SYSTEMC_LDLIBS = $(addprefix -l,${SYSTEMC_LIBRARIES})

define BUILD_COMPILER_FLAGS
   $(1)_CPPFLAGS += $$(addprefix -I,$${$(1)_INCLUDEDIR})
#   $$(warning $(1)_CPPFLAGS = $$($(1)_CPPFLAGS))
   $(1)_LDFLAGS += $$(addprefix -L,$${$(1)_LIBRARYDIR})
#   $$(warning $(1)_LDFLAGS = $$($(1)_LDFLAGS))
   $(1)_LDLIBS += $$(addprefix -l,$${$(1)_LIBRARIES})
#   $$(warning $(1)_LDLIBS = $$($(1)_LDLIBS))
endef

$(foreach dep,$(DEPENDENCIES),$(eval $(call BUILD_COMPILER_FLAGS,$(dep))))


################################
# Core of the Makefile

CPPFLAGS += $(foreach dep,$(DEPENDENCIES),${${dep}_CPPFLAGS})
LDFLAGS += $(foreach dep,$(DEPENDENCIES),${${dep}_LDFLAGS})
LDLIBS += $(foreach dep,$(DEPENDENCIES),${${dep}_LDLIBS})

${MODULE}: $(OBJS)

#clean:
#	rm -f $(OBJS) ${MODULE}
