# Directory where this Makefile is located
TOP := $(dir $(lastword $(MAKEFILE_LIST)))

GREENREG_DIR := $(TOP)

# Try to find dependencies automatically
-include $(TOP)/../Makefile.greensocs


# Set dependencies manually if above fails

GSGPSOCKET_DIR   ?= /Users/schroede/mydev/greensocs_gsgpsocket
GREENSOCKET_DIR   ?= /Users/schroede/mydev/greensocs_greensocket
GREENCONTROL_DIR   ?= /Users/schroede/mydev/greensocs_greencontrol
BOOST_DIR       ?= /cad/tools/boost
SYSTEMC_HOME    ?= /cad/tools/systemc
TLM_HOME        ?= /Users/schroede/mydev/TLM-2008-06-09

MYOBJDIR = $(GREENREG_DIR)/objs
SYSTEMC_INC_DIR = $(SYSTEMC_HOME)/include
TLM_INC_DIR     = $(TLM_HOME)/include/tlm

FLAGS    = -DSC_INCLUDE_DYNAMIC_PROCESSES -DSC_USE_STD_STRING -DLINUX -D__LINUX__ -O0 -g3 -Wall -m32 -c -fmessage-length=0    # removed: -DSYSTEMC_2_2

INCDIRS  =  -I . \
            -I $(SYSTEMC_INC_DIR)   \
            -I $(TLM_INC_DIR)   \
            -I $(BOOST_DIR)   \
            -I $(GSGPSOCKET_DIR)  \
            -I $(GREENSOCKET_DIR)  \
            -I $(GREENCONTROL_DIR)  \
            -I $(GREENREG_DIR)  \

            #-I $(GREENREG_DIR)/framework/core/analysis \
            #-I $(GREENREG_DIR)/framework/core \
            #-I $(GREENREG_DIR)/framework/devices   \
            #-I $(GREENREG_DIR)/framework/registers  \
            #-I $(GREENREG_DIR)/sysc_ext/kernel  \
            #-I $(GREENREG_DIR)/sysc_ext/utils  \
            #-I $(GREENREG_DIR)/sysc_ext/communication  \
            #-I $(GREENREG_DIR)/internal/device   \
            #-I $(GREENREG_DIR)/internal/registers/register   \
            #-I $(GREENREG_DIR)/internal/registers/bit   \
            #-I $(GREENREG_DIR)/internal/registers/register_data   \
            #-I $(GREENREG_DIR)/internal/registers/bit_range   \
            #-I $(GREENREG_DIR)/internal/registers   \
            #-I $(GREENREG_DIR)/greenreg_socket   \
            #-I $(GREENREG_DIR)/utils   \
            #-I $(GREENREG_DIR)/utils/stl_ext   \
            #-I $(GREENREG_DIR)/utils/patterns   \
            #-I $(GREENREG_DIR)/utils/storage \
            #-I $(GREENREG_DIR)/gs


CC = g++

